language: perl
perl:
   - "5.22"
   - "5.20"
   - "5.18"
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"
before_install:
   - export AUTOMATED_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
   - cpanm --quiet --notest Dist::Zilla
   - "dzil authordeps --missing | cpanm --quiet --notest"
   - "dzil listdeps --author --missing | cpanm --quiet"
script:
   - dzil smoke --release --author

sudo: false
