---
abstract: 'release Test::Version tests'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Test-Version
no_index:
  file:
    - perlcritic.rc
requires:
  Dist::Zilla::Plugin::InlineFiles: 0
  Moose: 0
  Test::Version: 0.04
  perl: 5.006
resources:
  bugtracker: http://github.com/xenoterracide/Dist-Zilla-Plugin-Test-Version/issues
  repository: git://github.com/xenoterracide/Dist-Zilla-Plugin-Test-Version.git
version: 0.1.3
